services:
    backend:
        build:
            context: .
            dockerfile: devops/backend/Dockerfile
            args:
                PORT_BACKEND: ${PORT_BACKEND}
        environment:
            - PORT_BACKEND=${PORT_BACKEND}
            - PORT_FRONTEND=${PORT_FRONTEND}
            - APP_ENV=${APP_ENV}
            - ROUTE_PREFIX=${ROUTE_PREFIX}
            - KEY_VAULT_URI=${KEY_VAULT_URI}
            - TENANT_ID=${TENANT_ID}
            - CLIENT_ID=${CLIENT_ID}
            - CLIENT_SECRET=${CLIENT_SECRET}
        image: backend_image
        container_name: backend_container
        ports:
            - '${PORT_BACKEND}:${PORT_BACKEND}'
        privileged: true
    frontend:
        build:
            context: .
            dockerfile: devops/frontend/Dockerfile
            args:
                APP_ENV: ${APP_ENV}
                PORT_FRONTEND: ${PORT_FRONTEND}
        environment:
            - CYPRESS_INSTALL_BINARY=0
            - APP_ENV=${APP_ENV}
            - PORT_FRONTEND=${PORT_FRONTEND}
        image: frontend_image
        container_name: frontend_container
        ports:
            - '${PORT_FRONTEND}:${PORT_FRONTEND}'
        depends_on:
            - backend
